### ISSUE TITLE
How to post a http request without cookie in headers?

### ISSUE THREAD

**Issue by cyhzju** [pact-foundation/pact-python#309] opened 2022-09-28 10:05 UTC
Here is my pact file
~~~
    {
  "consumer": {
    "name": "consumer"
  },
  "provider": {
    "name": "provider"
  },
  "interactions": [
    {
      "description": "for pact",
      "providerState": "test service.",
      "request": {
        "method": "post",
        "path": "/uri",
        "headers": {
          "Content-Type": "application/json"
        },
        "body": {
          "key": "value"
        }
      },
      "response": {
        "status": 200,
        "body": {
          "key": "value"
          }
        }
      }
    }
  ],
  "metadata": {
    "pactSpecification": {
      "version": "2.0.0"
    }
  }
}
~~~
And get the header of post request by wireshark :
   ~~~
  POST /uri HTTP/1.1
Cookie: 
Host: 127.0.0.1:8080
Content-Length: 57
Content-Type: application/json 
   ~~~
Due to the exist of `Cookie` in header, my provider can not response correctly. How can I remove it from header?

**Comment by mefellows** [comment] 2022-09-28 11:39
Interesting. That does seem like surprising behaviour from Pact, but also - why is your provider breaking with the presence of an empty header?

**Comment by mefellows** [comment] 2022-09-29 06:45
Yep, just confirmed for myself. @bethesque any ideas as to why there is an empty cookie header coming from the `pact-provider-verifier` CLI?

I can't imagine this is new behaviour and this is the first time I've seen a bug like this. 

I'd strongly recommend you get to the bottom of your error - it seems like Pact has inadvertently found an issue with your service. Obligatory reading on the topic of building resilient services ;) https://en.wikipedia.org/wiki/Robustness_principle

**Comment by bethesque** [comment] 2022-09-29 06:50
No idea why the cookie header is there. I'll have a look at rack test.

**Comment by mefellows** [comment] 2022-09-29 10:07
Thanks!

**Comment by bethesque** [comment] 2022-09-30 01:17
Looks like it sets a blank cookie for every request. Unfortunately, there's nothing the pact library can do about that.

https://github.com/rack/rack-test/blob/v1.1.0/lib/rack/mock_session.rb#L27

**Comment by mefellows** [comment] 2022-10-03 22:14
Closing as a won't fix.

**Closed by mefellows** 2022-10-03 22:14 UTC
