### ISSUE TITLE
Support V3 Features

### ISSUE THREAD

**Issue by samanthalcombs** [pact-foundation/pact-python#312] opened 2022-10-13 18:08 UTC
Are there plans to support V3 specifications of Pact? Our other microservices in Java run on V3 and it causes inconsistencies - especially when it comes to publishing the verification status on the pact broker.

**Comment by HendrikLeier** [comment] 2022-10-13 18:09
+1

**Comment by elliottmurray** [comment] 2022-10-14 08:05
So we have had a few attempts that didn't get traction. To get the FFI bindings working is a bit fiddly and a reasonable time investment. Just have been busy personally so haven't been able to dedicate time to this - apologies. Am aware of the need!

**Comment by YOU54F** [comment] 2022-10-14 10:21
Project tracking is here

https://github.com/pact-foundation/pact-python/projects/1

You can use the standalone verifier as an interim measure

https://docs.pact.io/implementation_guides/cli#native-binary-new

If anyone would like to offer support, please reach out!

**Comment by YOU54F** [comment] 2023-05-03 17:35
I'm going to close this as a dupe of #88 

I think we are still in need of contributors, in order to support pact v3 and beyond, and that thread has been open for longer

We are severely lacking in willing participants, and we are happy to lend a hand in moving things forward <3

If you would love to practise some python and become a pythonista, or you are a seasoned pythonista, drop into #88 and give us a shout!

**Closed by YOU54F** 2023-05-03 17:35 UTC
Labels: enhancement
