### ISSUE TITLE
Support for Pact specification v3

### ISSUE THREAD

**Issue by mrlubos** [pact-foundation/pact-python#240] opened 2021-07-01 08:53 UTC
Hey there! Are you planning to add support for Pact v3 which is currently in beta?

**Comment by mefellows** [comment] 2021-07-01 11:52
So v3 itself is not beta, but the Pact JS [beta](https://github.com/pact-foundation/pact-js#pact-js-v3) obviously is.

Going to close this as it's a duplicate of #88.

**Closed by mefellows** 2021-07-01 11:52 UTC
