### ISSUE TITLE
`make test` is not running properly on Python 3.6.2

### ISSUE THREAD

**Issue by jceplaras** [pact-foundation/pact-python#55] opened 2017-10-13 03:24 UTC
Running `make test` on virtualenv with Python 3.6.2 does not completely run the tests.

Output:
```
Process Process-8:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jceplaras/Projects/pact-python/virtualenv/lib/python3.6/site-packages/flake8/checker.py", line 666, in _run_checks_from_queue
    checker.run_checks(results_queue, statistics_queue)
  File "/home/jceplaras/Projects/pact-python/virtualenv/lib/python3.6/site-packages/flake8/checker.py", line 606, in run_checks
    self.run_ast_checks()
  File "/home/jceplaras/Projects/pact-python/virtualenv/lib/python3.6/site-packages/flake8/checker.py", line 510, in run_ast_checks
    checker = self.run_check(plugin, tree=ast)
  File "/home/jceplaras/Projects/pact-python/virtualenv/lib/python3.6/site-packages/flake8/checker.py", line 464, in run_check
    return plugin['plugin'](**arguments)
  File "/home/jceplaras/Projects/pact-python/virtualenv/lib/python3.6/site-packages/flake8/plugins/pyflakes.py", line 74, in __init__
    withDoctest=with_doctest)
  File "/home/jceplaras/Projects/pact-python/virtualenv/lib/python3.6/site-packages/pyflakes/checker.py", line 495, in __init__
    self.runDeferred(self._deferredFunctions)
  File "/home/jceplaras/Projects/pact-python/virtualenv/lib/python3.6/site-packages/pyflakes/checker.py", line 532, in runDeferred
    handler()
  File "/home/jceplaras/Projects/pact-python/virtualenv/lib/python3.6/site-packages/pyflakes/checker.py", line 1160, in runFunction
    self.handleNode(stmt, node)
  File "/home/jceplaras/Projects/pact-python/virtualenv/lib/python3.6/site-packages/pyflakes/checker.py", line 863, in handleNode
    handler(node)
  File "/home/jceplaras/Projects/pact-python/virtualenv/lib/python3.6/site-packages/pyflakes/checker.py", line 816, in handleChildren
    self.handleNode(node, tree)
  File "/home/jceplaras/Projects/pact-python/virtualenv/lib/python3.6/site-packages/pyflakes/checker.py", line 863, in handleNode
    handler(node)
  File "/home/jceplaras/Projects/pact-python/virtualenv/lib/python3.6/site-packages/pyflakes/checker.py", line 816, in handleChildren
    self.handleNode(node, tree)
  File "/home/jceplaras/Projects/pact-python/virtualenv/lib/python3.6/site-packages/pyflakes/checker.py", line 863, in handleNode
    handler(node)
  File "/home/jceplaras/Projects/pact-python/virtualenv/lib/python3.6/site-packages/pyflakes/checker.py", line 1017, in GENERATOREXP
    self.handleChildren(node)
  File "/home/jceplaras/Projects/pact-python/virtualenv/lib/python3.6/site-packages/pyflakes/checker.py", line 816, in handleChildren
    self.handleNode(node, tree)
  File "/home/jceplaras/Projects/pact-python/virtualenv/lib/python3.6/site-packages/pyflakes/checker.py", line 862, in handleNode
    handler = self.getNodeHandler(node.__class__)
  File "/home/jceplaras/Projects/pact-python/virtualenv/lib/python3.6/site-packages/pyflakes/checker.py", line 696, in getNodeHandler
    self._nodeHandlers[node_class] = handler = getattr(self, nodeType)
AttributeError: 'FlakesChecker' object has no attribute 'JOINEDSTR'
```

Steps to replicate
1. Create virtualenv with Python 3.6.2
2. Run `make test`

- Python version: 3.6.2
- Flake8 version: 3.2.1 (mccabe: 0.5.2, pycodestyle: 2.2.0, pyflakes: 1.3.0) CPython 3.6.2 on Linux

**Comment by ftobia** [comment] 2017-11-20 21:53
I am unable to reproduce.

Steps:

1. `git clone git@github.com:pact-foundation/pact-python.git`
1. `docker run --rm -it --volume `pwd`/pact-python:/src --workdir /src python:3.6 /bin/bash`
1. `pip install tox`
1. `tox -e py36-test`

Result:

```
...
root@ae7385961287:/src# tox -e py36-test
GLOB sdist-make: /src/setup.py
py36-test create: /src/.tox/py36-test
py36-test installdeps: -rrequirements_dev.txt
py36-test inst: /src/.tox/dist/pact-python-0.10.0.zip
py36-test installed: certifi==2017.11.5,chardet==3.0.4,click==6.7,codecov==2.0.5,configparser==3.5.0,coverage==4.3.4,enum34==1.1.6,flake8==3.2.1,Flask==0.11.1,idna==2.6,itsdangerous==0.24,Jinja2==2.10,MarkupSafe==1.0,mccabe==0.5.2,mock==2.0.0,nose==1.3.7,pact-python==0.10.0,pbr==3.1.1,pluggy==0.5.2,psutil==5.4.1,py==1.5.2,pycodestyle==2.2.0,pydocstyle==1.1.1,pyflakes==1.3.0,requests==2.18.4,six==1.11.0,tox==2.5.0,tox-travis==0.8,urllib3==1.22,virtualenv==15.1.0,Werkzeug==0.12.2
py36-test runtests: PYTHONHASHSEED='2919336942'
py36-test runtests: commands[0] | nosetests
...........................................................................................
Name                  Stmts   Miss Branch BrPart  Cover
-------------------------------------------------------
pact.py                   6      0      0      0   100%
pact/__version__.py       1      0      0      0   100%
pact/constants.py        12      0      4      0   100%
pact/consumer.py         10      0      2      0   100%
pact/matchers.py         37      0     14      0   100%
pact/pact.py            121      0     26      0   100%
pact/provider.py          3      0      0      0   100%
pact/verify.py           57      4     32      1    92%
-------------------------------------------------------
TOTAL                   247      4     78      1    98%
----------------------------------------------------------------------
Ran 91 tests in 1.847s

OK
_________________________________________________________________________ summary _________________________________________________________________________
  py36-test: commands succeeded
  congratulations :)
```

Python version: 3.6.3

**Comment by matthewbalvanz-wf** [comment] 2017-11-21 04:22
I tried to reproduce this issue today as well and saw passing tests. A similar stack trace was reported in the flake8 project [some time ago](https://gitlab.com/pycqa/flake8/issues/240), but the fix should be included in the versions everyone is using here. Is there any chance a different version could be available in the environment when the tests are running?

I can take a look around the pact-python code a bit, but unless we can identify the line its encountering the issue on and rewrite it to be something that doesn't cause this error I'm not sure how we could resolve it without assistance from the pyflakes team.

**Comment by elliottmurray** [comment] 2021-05-03 14:58
Closing as not re-raised

**Closed by elliottmurray** 2021-05-03 14:58 UTC
